export const C1SectionQuestions = {
    'Medical coding and billing which relates to the standardized medical coding systems used to represent diagnoses, procedures, services, products, and the processes involved in submitting and managing healthcare claims': [
        'A030',
        'A033',
        'A034',
        'A035',
        'A037',
        'A057',
        'A064',
        'B003',
        'B013',
        'B017',
        'B020',
        'B021',
        'B040',
        'B048',
    ],
    'Government and commercial healthcare coverage policies and procedures, including benefit design, denials and appeals, and utilization management strategies': [
        'A001',
        'A009',
        'A016',
        'A023',
        'A067',
        'A072',
        'A080',
        'A090',
        'A091',
        'B008',
        'B014',
        'B027',
        'B028',
        'B047',
        'B059',
    ],
    'Payment and reimbursement, including reimbursement models, rates and incentive programs': [
        'A039',
        'A042',
        'A045',
        'A047',
        'B016',
        'B025',
        'B062',
    ],
    'Pricing and contracting, including pricing benchmarks, supply chain dynamics, regulatory compliance considerations, and the various stakeholders and their contracts': [
        'A051',
        'A097',
        'B004',
        'B058',
        'B064',
        'B072',
        'B073',
        'B074',
        'B075',
        'B085',
        'B087',
        'B091',
        'B093',
    ],
    'Product acquisition and distribution, including the buy and bill process, specialty pharmacy, and distribution channels': [
        'A010',
        'A099',
        'B053',
        'B055',
        'B056',
        'B061',
        'A096',
    ]
};